export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCEED = 'FETCH_ITEMS_SUCCEED';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';
export const POST_ITEM_START = 'POST_ITEM_START';
export const POST_ITEM_SUCCEED = 'POST_ITEM_SUCCEED';
export const POST_ITEM_FAIL = 'POST_ITEM_FAIL';
